### ISSUE TITLE
Email Not Received After Registration

### ISSUE THREAD

**Issue by AhmedFatthy1040** [activecourses/upwork-clone-backend#29]
### Description
When a user registers, a message indicates that an email has been sent for verification. However, users do not receive any email in their inbox. This issue needs investigation to determine if it's related to the code implementation or the email configuration settings.

### Steps to Reproduce
1. Attempt to register a new user account.
2. Observe the message stating that the email has been sent.
3. Check the inbox for the email; it is not received.

### Expected Behavior
After registering, the user should receive a verification email in their inbox.

### Actual Behavior
The application indicates that an email has been sent, but no email is received.

### Potential Areas to Investigate
1. **Email Sending Code**: Review the implementation in the authentication service responsible for sending emails. Ensure it handles sending correctly and logs any errors that may occur during the process.
2. **Email Configuration**: Check the email service configuration (SMTP settings) to ensure it is set up correctly. Verify that credentials, ports, and host settings are accurate.
3. **Email Provider Issues**: There might be issues with the email provider or the sender's address. Ensure that emails are not being sent to spam or filtered by the email provider.
4. **Logging**: Implement logging around the email sending process to capture any errors or issues that occur when attempting to send emails.

### Additional Notes
- If applicable, provide details about the email service provider used (e.g., SMTP server, third-party email service).
- Mention any relevant logs or error messages observed during the registration process or while sending the email.

### Suggested Next Steps
- Review the email sending code and configuration.
- Test the email functionality with different email addresses.
- Verify whether the emails are being sent and received in other inboxes or domains.

**Comment by AhmedMohamedAbdelaty** [comment]
I don't know much about email verification or its implementation, but I found that `MailConfig.java` does not import the package name. The second thing is that it gets the variables from `myconfig.properties`, which should be changed to `env.properties`, which can be found in the `/src/main/resources` folder. 

Lastly:
```
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=test@gmail.com
spring.mail.password=test
```
Of course this data should be updated with the email provider and the correct email and password for testing.

**Comment by AhmedFatthy1040** [comment]
I have included the myconfig.properties file in the .gitignore to protect sensitive information, such as my email and password.

**Comment by AhmedFatthy1040** [comment]
I will address the package name issue in my current open pull request.
